---
title: "Homeless Arcos"
author: "Howard Center for Investigative Journalism"
date: "10/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Libraries

```{r}
library(tidyverse)  # attaches purrr and readr
library(lubridate)
library(rvest)
library(downloader)
library(R.utils)
library(rlist)
library(arcos)
library(tidycensus)
# library(fs)
# library(stringr)

# library(retrosheet)
# install.packages('retrosheet')
# devtools::install_github("rmscriven/retrosheet")
```


```{r}

# Store census API key
census_api_key("549950d36c22ff16455fe196bbbd01d63cfbe6cf")

# store ARCOS API keys as an object called key
key <- "uO4EK6I"

# Define a list of states

states <- c("AL",	"AK",	"AZ",	"AR",	"CA",	"CO",	"CT", "DC", "DE",	"FL",	"GA",	"HI",	"ID",	"IL",	"IN",	"IA",	"KS",	"KY",	"LA",	"ME",	"MD",	"MA",	"MI",	"MN",	"MS",	"MO",	"MT",	"NE",	"NV",	"NH",	"NJ",	"NM",	"NY",	"NC",	"ND",	"OH",	"OK",	"OR",	"PA",	"RI",	"SC",	"SD",	"TN",	"TX",	"UT",	"VT",	"VA",	"WA",	"WV",	"WI",	"WY")

# Lowercase all of them for happy urls
states <- lapply(states, tolower)

# Build an empty list to hold the url for each state
state_urls <- list()

# Make an empty dataframe
tract_pills <- tibble(GEOID = character(), year = character(), total_pills = double(), total_2010_population = double())

# Build a list of URLS of zip files to download, with a for loop

for (state in states) {
    # Cut URL into pieces, this is my last resort. https://www.washingtonpost.com/wp-stat/dea-pain-pill-database/summary/arcos-wa-statewide-itemized.tsv.gz
    url_start <- "https://www.washingtonpost.com/wp-stat/dea-pain-pill-database/summary/arcos-"
    url_end <- "-statewide-itemized.tsv.gz"
    # Rebuild it with for each state code
    state_url <- paste0(url_start, state, url_end)
    # Add to our list of state urls
    state_urls <- c(state_urls, state_url)
}

# For debugging, just take first state
#state_urls <- state_urls

# Pull down raw data for each state, 
for (url in state_urls) {
    
    # Get the state code for purpose of creating filenames
    state_code <- url %>%
      str_remove("https://www.washingtonpost.com/wp-stat/dea-pain-pill-database/summary/arcos-") %>%
      str_remove("-statewide-itemized.tsv.gz")
    file_path <- paste0("input_data/",state_code,".tsv.gz")
    # Download each state file into our data folder
    download(url, file_path, mode="wb")  
    print(paste0("Finished downloading ", state_code))
    # Unzip each state file, which deletes the zip folder
    gunzip(file_path)
    print(paste0("Finished unzipping ", state_code))
    # Load census tract of each chain and retail pharmacy in our state in the data
    pharmacy_tracts <- pharm_tracts(key=key, state=state_code)
    print(paste0("Finished getting pharmacy tracts ", state_code))
    # Load 2010 population of each census tract in the data
    population_2010 <- get_decennial(geography = "tract", variables = "P001001", year = 2010,
                    state = state_code, geometry = FALSE) %>%
                    select(GEOID, total_2010_population = value)
    print(paste0("Finished getting population ", state_code))
    # Read in the raw data for each state 
    temp <- read_tsv(paste0("input_data/",state_code,".tsv"))
    print(paste0("Finished reading in raw data ", state_code))
    # Process the data to end up with a dataframe of total pills per year
    temp <- temp %>%
      # Make sure transaction date is a character.
      mutate(TRANSACTION_DATE = as.character(TRANSACTION_DATE)) %>%
      # Split out year from transaction date
      mutate(year = str_sub(TRANSACTION_DATE, 5,8)) %>%
      # Group by each pharmacy and year and count total pills
      group_by(BUYER_DEA_NO, year) %>%
      summarise(total_pills = sum(DOSAGE_UNIT)) %>%
      # Join grouped and summed data with file from WAPO ARCOS api that has tract info for chain and retail pharmacies.  Note: this will leave out non pharmacy shipments. 
      inner_join(pharmacy_tracts, by="BUYER_DEA_NO") %>%
      # Group by tract and year and sum total pills
      group_by(GEOID, year) %>%
      summarise(total_pills = sum(total_pills)) %>%
      # Join each tract/year combo to 2010 population in that tract  
      left_join(population_2010, by="GEOID") %>%
      # Put in the state 
      mutate(state = toupper(state_code)) %>%
      select(GEOID, state, everything())
    print(paste0("Finished processing data ", state_code))
    # Bind results into dataframe
    tract_pills <- tract_pills %>%
      bind_rows(temp)
    print(paste0("Finished adding results to dataframe", state_code))
    print(paste0("Done ", state_code,". GOTO next state"))
  
}


#write_csv(tract_pills, "data/tract_pills.csv")



```

## By Month and Year for Jazmin

```{r}

# Store census API key
#census_api_key("549950d36c22ff16455fe196bbbd01d63cfbe6cf")

# store ARCOS API keys as an object called key
key <- "uO4EK6I"

# Define a list of states

states <- c("AL",	"AK",	"AZ",	"AR",	"CA",	"CO",	"CT", "DC", "DE",	"FL",	"GA",	"HI",	"ID",	"IL",	"IN",	"IA",	"KS",	"KY",	"LA",	"ME",	"MD",	"MA",	"MI",	"MN",	"MS",	"MO",	"MT",	"NE",	"NV",	"NH",	"NJ",	"NM",	"NY",	"NC",	"ND",	"OH",	"OK",	"OR",	"PA",	"RI",	"SC",	"SD",	"TN",	"TX",	"UT",	"VT",	"VA",	"WA",	"WV",	"WI",	"WY")

# Lowercase all of them for happy urls
states <- lapply(states, tolower)

# Build an empty list to hold the url for each state
state_urls <- list()

# Make an empty dataframe for pill totals and ppp for each county for each month for each year.
#pills_county_month_year <- tibble(countyfips = character(), BUYER_COUNTY = character(), BUYER_STATE = character(), year = character(), month=character(), #total_pills = double(), population=integer(), pills_per_person_county_month_year=double())

# Make an empty dataframe for pill totals and ppp for each county in each month (i.e. grouping all Januarys together)
#pills_county_month <- tibble(countyfips = character(), BUYER_COUNTY = character(), BUYER_STATE = character(), month=character(), total_pills = double(), #average_annual_population=double(), pills_per_person_county_month=double())

# Make an empty dataframe for pill totals and ppp for each state for each month for each year (i.e. grouping all Januarys together).
#pills_state_month <- tibble(BUYER_STATE = character(), month=character(), total_pills = double(), average_annual_population=double(), pills_per_person_state_month=double())

# Make an empty dataframe for pill totals and ppp for each state for entire period (for checking)
#pills_state <- tibble(BUYER_STATE = character(), total_pills = double(), average_annual_population=double(), pills_per_person_state=double())

# Build a list of URLS of zip files to download, with a for loop

for (state in states) {
    # Cut URL into pieces, this is my last resort. https://www.washingtonpost.com/wp-stat/dea-pain-pill-database/summary/arcos-wa-statewide-itemized.tsv.gz
    url_start <- "https://www.washingtonpost.com/wp-stat/dea-pain-pill-database/summary/arcos-"
    url_end <- "-statewide-itemized.tsv.gz"
    # Rebuild it with for each state code
    state_url <- paste0(url_start, state, url_end)
    # Add to our list of state urls
    state_urls <- c(state_urls, state_url)
}

# For debugging, just take first state
state_urls <- state_urls[31:51]
#state_urls
# url <- "https://www.washingtonpost.com/wp-stat/dea-pain-pill-database/summary/arcos-ak-statewide-itemized.tsv.gz"

# Pull down raw data for each state, 
for (url in state_urls) {
    
    # Get the state code for purpose of creating filenames
    state_code <- url %>%
      str_remove("https://www.washingtonpost.com/wp-stat/dea-pain-pill-database/summary/arcos-") %>%
      str_remove("-statewide-itemized.tsv.gz")
    #file_path <- paste0("input_data/",state_code,".tsv.gz")
    # Download each state file into our data folder
    #download(url, file_path, mode="wb")  
    #print(paste0("Finished downloading ", state_code))
    # Unzip each state file, which deletes the zip folder
    #gunzip(file_path)
    #print(paste0("Finished unzipping ", state_code))
    # Load census tract of each chain and retail pharmacy in our state in the data
    #pharmacy_tracts <- pharm_tracts(key=key, state=state_code)
    #print(paste0("Finished getting pharmacy tracts ", state_code))
    # Load population of each census county in the data by year
    population <- county_population(state=state_code, key=key) %>%
      mutate(year = as.character(year))
    #buyer_addresses <- buyer_addresses(state=state_code, key=key)
    #print(paste0("Finished getting population ", state_code))
    # Read in the raw data for each state 
    temp <- read_tsv(paste0("input_data/",state_code,".tsv"))
    print(paste0("Finished reading in raw data ", state_code))
    # Process the data to end up with a dataframe of total pills per county per month year
    temp <- temp %>%
      # Make sure transaction date is a character.
      mutate(TRANSACTION_DATE = as.character(TRANSACTION_DATE)) %>%
      # Split out year from transaction date
      mutate(year = str_sub(TRANSACTION_DATE, 5,8)) %>%
      # Split out month from transaction date
      mutate(month = str_sub(TRANSACTION_DATE, 1,2)) %>%
      # Group by each pharmacy and year and count total pills
      group_by(BUYER_COUNTY, BUYER_STATE, year, month) %>%
      summarise(total_pills = sum(DOSAGE_UNIT)) %>% 
      # Join to population data 
      inner_join(population, by=c("BUYER_COUNTY", "BUYER_STATE", "year")) %>%
      select(countyfips, BUYER_COUNTY, BUYER_STATE, year, month, total_pills, population) %>%
      # Make pills per person stat
      mutate(pills_per_person_county_month_year = total_pills/population) %>%
      filter(!is.na(population)) %>%
      filter(!is.na(total_pills))
    print(paste0("Finished processing data ", state_code))
    # Bind results into dataframe
    pills_county_month_year <- pills_county_month_year %>%
      bind_rows(temp)
    print(paste0("Finished adding results to first dataframe ", state_code))
    # Modify population 
    population <- population %>%
      group_by(BUYER_COUNTY, BUYER_STATE, countyfips) %>%
      filter(!is.na(population)) %>%
      summarise(average_annual_population = round(mean(population),0))
    # Modify temp again to get county by month
    temp <- temp %>%
      group_by(countyfips, BUYER_COUNTY, BUYER_STATE, month) %>%
      summarise(total_pills = sum(total_pills)) %>% 
      filter(!is.na(total_pills)) %>%
      inner_join(population, by=c("countyfips", "BUYER_COUNTY", "BUYER_STATE")) %>%
      mutate(pills_per_person_county_month = total_pills/average_annual_population)
    # Bind results into dataframe
    pills_county_month <- pills_county_month %>%
      bind_rows(temp)  
    print(paste0("Finished adding results to second dataframe ", state_code))
    # Modify population 
    population <- population %>%
      group_by(BUYER_STATE) %>%
      filter(!is.na(average_annual_population)) %>%
      summarise(average_annual_population = round(sum(average_annual_population),0))
    # Modify temp again to get state by month
    temp <- temp %>%
      group_by(BUYER_STATE, month) %>%
      summarise(total_pills = sum(total_pills)) %>% 
      inner_join(population, by=c("BUYER_STATE")) %>%
      mutate(pills_per_person_state_month = total_pills/average_annual_population)
    # Bind results into dataframe
    pills_state_month <- pills_state_month %>%
      bind_rows(temp)  
    print(paste0("Finished adding results to third dataframe ", state_code))
    # Modify population 
    population <- population 
    # Modify temp again to get state by month
    temp <- temp %>%
      group_by(BUYER_STATE) %>%
      summarise(total_pills = sum(total_pills)) %>% 
      inner_join(population, by=c("BUYER_STATE")) %>%
      mutate(pills_per_person_state = round(total_pills/average_annual_population,2))
    # Bind results into dataframe
    pills_state <- pills_state %>%
      bind_rows(temp)  
    print(paste0("Finished adding results to fourth dataframe ", state_code))
    # Go to next state
    print(paste0("Done ", state_code,". GOTO next state"))
    # Close open connections because otherwise it gets fucked
    closeAllConnections()
}


# write_csv(tract_pills, "data/tract_pills.csv")

write_csv(pills_county_month, "data/pills_county_month.csv")
write_csv(pills_county_month_year, "data/pills_county_month_year.csv")
write_csv(pills_state, "data/pills_state.csv")
write_csv(pills_state_month, "data/pills_state_month.csv")



```

